export { ReactComponent as InfoIcon } from './info.svg'
export { ReactComponent as ShowIcon } from './show.svg'
export { ReactComponent as HideIcon } from './hide.svg'
export { ReactComponent as ErrorIcon } from './error.svg'
export { ReactComponent as CloseIcon } from './close.svg'
export { ReactComponent as WarningIcon } from './warning.svg'
export { ReactComponent as TickPrimaryIcon } from './tick.svg'
